- name: Configure Azure VM
  hosts: azure_vm
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Node Exporter
      become: true
      shell: |
       curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
       tar xvfz node_exporter-1.7.0.linux-amd64.tar.gz
       sudo mv node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
       rm -rf node_exporter*

    - name: Create systemd service for Node Exporter
      become: true
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=nobody
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target

    - name: Start and enable Node Exporter
      become: true
      systemd:
        name: node_exporter
        enabled: yes
        state: started

