---
- name: Deploy Prometheus and Grafana on Azure
  hosts: localhost
  connection: local
  vars:
    prometheus_container:
      name: prometheus
      image: prom/prometheus
      cpu: 1
      memory: 1.5
      port: 9090

    grafana_container:
      name: grafana
      image: grafana/grafana
      cpu: 1
      memory: 1.5
      port: 3000

  collections:
    - azure.azcollection

  tasks:
    - name: Create Prometheus container group
      azure.azcollection.azure_container_instance:
        name: prometheus-group
        resource_group: azure-sre-lab-rg
        location: francecentral
        os_type: Linux
        containers:
          - name: "{{ prometheus_container.name }}"
            image: "{{ prometheus_container.image }}"
            cpu: "{{ prometheus_container.cpu }}"
            memory: "{{ prometheus_container.memory }}"
            ports:
              - "{{ prometheus_container.port }}"

    - name: Create Grafana container group
      azure.azcollection.azure_container_instance:
        name: grafana-group
        resource_group: azure-sre-lab-rg
        location: francecentral
        os_type: Linux
        containers:
          - name: "{{ grafana_container.name }}"
            image: "{{ grafana_container.image }}"
            cpu: "{{ grafana_container.cpu }}"
            memory: "{{ grafana_container.memory }}"
            ports:
              - "{{ grafana_container.port }}"