---
- name: Deploy Prometheus and Grafana on Azure
  hosts: localhost
  connection: local
  vars:
    prometheus_container:
      name: prometheus
      image: prom/prometheus
      cpu: 1
      memory: 1.5
      port: 9090

    grafana_container:
      name: grafana
      image: grafana/grafana
      cpu: 1
      memory: 1.5
      port: 3000

  collections:
    - azure.azcollection

  tasks:
    - name: Create Prometheus container group
      resource_group: "azure-sre-lab-rg"
      name: "prometheus-group"
      location: "francecentral"
      os_type: Linux
      containers:
        - name: prometheus
          image: prom/prometheus
          cpu: 1
          memory: 1.5
          ports:
            - 9090

    - name: Create Grafana container group
      azure.azcollection.azure_container_instance:
        resource_group: "azure-sre-lab-rg"
        name: "grafana-group"
        location: "francecentral"
        os_type: Linux
        containers:
          - name: grafana
            image: grafana/grafana
            cpu: 1
            memory: 1.5
            ports:
              - 3000