name: Ansible Deploy to Azure VM

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible, Azure SDK, and Azure Collection
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install ansible
        python3 -m pip install \
          azure-cli \
          azure-mgmt-resource \
          azure-mgmt-containerinstance \
          azure-identity \
          msrestazure
        ansible-galaxy collection install azure.azcollection
        echo -e "[defaults]\ncollections_path = ~/.ansible/collections:/usr/share/ansible/collections\nansible_python_interpreter = /usr/bin/python3" > ansible.cfg

    - name: Run Ansible Playbook
      run: |
        ANSIBLE_CONFIG=ansible.cfg ansible-playbook ansible/playbooks/deploy-monitoring.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_TENANT: ${{ secrets.ARM_TENANT_ID }}