name: Ansible Deploy to Azure VM

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible & Azure Collection
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass
        ansible-galaxy collection install azure.azcollection
        echo "collections_paths = ~/.ansible/collections:/usr/share/ansible/collections" > ansible.cfg

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbooks/deploy-monitoring.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"


    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbooks/deploy-monitoring.yml
        ANSIBLE_HOST_KEY_CHECKING: "False"