name: Ansible Deploy to Azure VM

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass

    - name: Install Azure Ansible Collection
      run: |
        mkdir -p ~/.ansible/collections
        ansible-galaxy collection install azure.azcollection -p ~/.ansible/collections
      env:
        ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections


    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbooks/deploy-monitoring.yml -i ansible/hosts
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"