name: Terraform Destroy

on:
  workflow_dispatch:  
jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Destroy
      run: |
        cd terraform
        terraform destroy -auto-approve \
          -var-file="terraform.tfvars" \
          -var "ssh_public_key=${SSH_PUBLIC_KEY}"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
